Bugfix/nb 28 hanging interpreters
digitalreasoning/incubator-zeppelin pull request #18
Opened 2016-10-26 15:35 UTC by christianreynoldsDR

### What is this PR for?
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - https://zeppelin.apache.org/contribution/contributions.html

### What type of PR is it?
[Bug Fix | Improvement | Feature | Documentation | Hot Fix | Refactoring]

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN/
* Put link here, and add [ZEPPELIN-*Jira number*] in PR title, eg. [ZEPPELIN-533]

### How should this be tested?
Outline the steps to test the PR here.

### Screenshots (if appropriate)

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

2016-10-26 15:50 UTC, jbunting requested changes
Just a few thoughts on improvement.

2016-10-26 15:50 UTC, jbunting commented on zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreter.java
> +        future.cancel(true);
We should log something here...

2016-10-26 15:50 UTC, jbunting commented on zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreter.java
> +      sleep(5000);
How hard to make these timeouts configurable?

2016-10-26 15:50 UTC, jbunting commented on zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/RemoteInterpreterService.java
> +        return getCursor();
Why are we making this change?

2016-10-26 15:50 UTC, jbunting commented on zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreter.java
> +        status = Runtime.getRuntime().exec("kill -0 " + pid).waitFor();
It might be clearer to pull this block into a `boolean isProcessUp(int pid)` method.

2016-10-26 15:50 UTC, jbunting commented on zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreter.java
> +        future.cancel(true);
In fact, we should log every time we try a new "force kill" effort...

2016-10-26 15:50 UTC, jbunting commented on zeppelin-interpreter/pom.xml
> +      <version>4.1.0</version>
Any reason not to use 4.2.2? (http://search.maven.org/#artifactdetails%7Cnet.java.dev.jna%7Cjna%7C4.2.2%7Cjar)

2016-10-26 15:51 UTC, WLPhoenix commented on zeppelin-interpreter/pom.xml
> +      <version>4.1.0</version>
Any reason for going w/ `4.1.0` instead of `4.2.2`?

2016-10-26 15:51 UTC, WLPhoenix commented on zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreter.java
> +    try
Probably want to match bracing style to the zeppelin project.

2016-10-26 16:39 UTC, maheshmt commented on zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreter.java
> +        future.cancel(true);
Do we know if thread interrupting Client.close() will actually kill that thread?

FYI, this is what a thread dump looks like for Client waiting for recv_close event from the other process. Looks like it holds a lock internally. Although in the end the kill/kill 9 will probably make that recv_close error out.
`"Thread-879" #1041 prio=5 os_prio=0 tid=0x00007fc57c012800 nid=0x8a81 runnable [0x00007fc9247cc000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x00000000d63de920> (a java.io.BufferedInputStream)
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client.recv_close(RemoteInterpreterService.java:226)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client.close(RemoteInterpreterService.java:212)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.close(RemoteInterpreter.java:237)`

2016-10-27 17:35 UTC, jbunting approved these changes

2016-10-27 17:35 UTC, merged